### ISSUE TITLE
validity-aeson fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [NorfairKing/validity#99]
```
validity-aeson                 > /tmp/stack-c3c07f9871ea1838/validity-aeson-0.2.0.4/src/Data/Validity/Aeson.hs:15:27: error:
validity-aeson                 >     • No instance for (Validity Object)
validity-aeson                 >         arising from a use of ‘annotate’
validity-aeson                 >     • In the expression: annotate o "Object"
validity-aeson                 >       In an equation for ‘validate’:
validity-aeson                 >           validate (Object o) = annotate o "Object"
validity-aeson                 >       In the instance declaration for ‘Validity Value’
validity-aeson                 >    |
validity-aeson                 > 15 |     validate (Object o) = annotate o "Object"
validity-aeson                 >    |                           ^^^^^^^^^^^^^^^^^^^
```

**Comment by NorfairKing** [comment]
Hm, do you have an `extra-deps` section for me to test this with?

**Comment by juhp** [comment]
Well you could just list `- aeson-2.0.2.0` there or
like me use `stack --resolver nightly build aeson-2.0.2.0 .` say etc.

**Comment by Bodigrim** [comment]
As a Hackage trustee I made revisions to prohibit unbuildable configurations:

https://hackage.haskell.org/package/validity-aeson-0.0.0.0/revisions/
https://hackage.haskell.org/package/validity-aeson-0.2.0.1/revisions/
https://hackage.haskell.org/package/validity-aeson-0.2.0.2/revisions/
https://hackage.haskell.org/package/validity-aeson-0.2.0.3/revisions/
https://hackage.haskell.org/package/validity-aeson-0.2.0.4/revisions/

**Comment by NorfairKing** [comment]
Fixed in the latest release.
