### ISSUE TITLE
genvalidity-hspec doesn't build with hspec 2.10

### ISSUE THREAD

**Issue by felixonmars** [NorfairKing/validity#106]
```
[ 2 of 13] Compiling Test.Validity.Utils ( src/Test/Validity/Utils.hs, dist/build/Test/Validity/Utils.dyn_o )

src/Test/Validity/Utils.hs:71:57: error:
    • Couldn't match type: [SpecTree b]
                     with: (base-4.15.1.0:Data.Semigroup.Internal.Endo Config,
                            [SpecTree b])
      Expected: (r,
                 (base-4.15.1.0:Data.Semigroup.Internal.Endo Config, [SpecTree a]))
                -> (r,
                    (base-4.15.1.0:Data.Semigroup.Internal.Endo Config, [SpecTree b]))
        Actual: (r, [SpecTree a]) -> (r, [SpecTree b])
    • In the first argument of ‘fmap’, namely ‘(second (map f))’
      In the first argument of ‘mapWriterT’, namely
        ‘(fmap (second (map f)))’
      In the first argument of ‘SpecM’, namely
        ‘(mapWriterT (fmap (second (map f))) specs)’
    • Relevant bindings include
        f :: SpecTree a -> SpecTree b
          (bound at src/Test/Validity/Utils.hs:71:14)
        mapSpecTree' :: (SpecTree a -> SpecTree b)
                        -> SpecM a r -> SpecM b r
          (bound at src/Test/Validity/Utils.hs:71:1)
   |
71 | mapSpecTree' f (SpecM specs) = SpecM (mapWriterT (fmap (second (map f))) specs)
   |                                                         ^^^^^^^^^^^^^^
```

**Comment by NorfairKing** [comment]
PR welcome!
