### PR TITLE
Add GHC 9.2 support

### LINKED ISSUE #99: validity-aeson fails to build with aeson-2.0
```
validity-aeson                 > /tmp/stack-c3c07f9871ea1838/validity-aeson-0.2.0.4/src/Data/Validity/Aeson.hs:15:27: error:
validity-aeson                 >     • No instance for (Validity Object)
validity-aeson                 >         arising from a use of ‘annotate’
validity-aeson                 >     • In the expression: annotate o "Object"
validity-aeson                 >       In an equation for ‘validate’:
validity-aeson                 >           validate (Object o) = annotate o "Object"
validity-aeson                 >       In the instance declaration for ‘Validity Value’
validity-aeson                 >    |
validity-aeson                 > 15 |     validate (Object o) = annotate o "Object"
validity-aeson                 >    |                           ^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by srid**
- Sized Word/Int changes: https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.2#sized-wordint-use-sized-wordint-primitives
- Aeson 2's KeyMap/Key types are new: https://github.com/haskell/aeson/issues/881#issuecomment-944920664 (also resolves #99)
- Use https://github.com/yesodweb/persistent/pull/1338

### CODE REVIEW

**Comment by srid** [comment]
I don't know if I got the instances right.

**Comment by NorfairKing** [comment]
The instances look right to me!

**Comment by ocharles** [comment]
Hi all, any chance of this being merged and released? It's preventing me from using `ghc-debug-brick`, as that depends on `cursor` which depends on `validity`.

**Comment by NorfairKing** [comment]
@ocharles I cannot put this in CI yet because there's no nixpkgs version that uses GHC 9.2 yet, but I could "hope" that it just works and release anyway. Soonest would be monday though.

**Comment by ocharles** [comment]
Fair enough. Haskell.nix has 9.2.2, though that's a bit of extra work

**Comment by srid** [comment]
nixpkgs has 9.2.1 - but not as default (things may not be cached):

```
❯ nix-env -f "<nixpkgs>" -qaP -A haskell.compiler | grep -E '(921|9\.2\.1)' | grep -v integer
haskell.compiler.ghc921                  ghc-9.2.1
```

**Comment by NorfairKing** [comment]
More or less to be expected: this doesn't build (with `--pedantic`) or pass tests (infinite loop in `genvalidity-aeson`). I'll see what I can do.

**Comment by NorfairKing** [comment]
In particular `stack test genvalidity-aeson` currently hangs for GHC 9.2.1 but not the current version.

**Comment by Bodigrim** [comment]
As a Hackage trustee I made necessary revisions to prohibit invalid build plans:

https://hackage.haskell.org/package/validity-0.12.0.0/revisions/
https://hackage.haskell.org/package/validity-0.11.0.1/revisions/
https://hackage.haskell.org/package/validity-0.11.0.0/revisions/
https://hackage.haskell.org/package/validity-0.10.0.0/revisions/

**Comment by srid** [comment]
@NorfairKing Everything should be fixed now.

(`nix-build ci.nix` did run successfully, IIRC, but it is not using GHC 9 I think)

**Comment by srid** [comment]
> [64a9450](https://github.com/NorfairKing/validity/pull/100/commits/64a9450a849e6bc30a80dc1aa3c42eae90d7c09c)

This was a self-own. Just because it got compiled doesn't mean it was _correct_.

**Comment by NorfairKing** [comment]
Merged as part of #104 , ty!
