### ISSUE TITLE
genvalidity-hspec fails to build with ghc-9.6

### ISSUE THREAD

**Issue by juhp** [NorfairKing/validity#114]
```
       Building library for genvalidity-hspec-1.0.0.2..                                                                             
       [ 2 of 13] Compiling Test.Validity.Utils                   
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/genvalidity-hspec-1.0.0.2-a2965915e52919df47f085750878e3b214d433e22e679d59657c4fd4e4f9
00b8/src/Test/Validity/Utils.hs:110:34: error:                    
           Ambiguous occurrence ‘Reason’                                                                                            
           It could refer to                                                                                                        
              either ‘Test.Hspec.Core.Formatters.Reason’,                                                                           
                     imported from ‘Test.Hspec.Core.Formatters’ at src/Test/Validity/Utils.hs:27:1-33
                     (and originally defined in ‘hspec-core-2.11.1:Test.Hspec.Core.Formatters.V1.Monad’)                            
                  or ‘Test.Hspec.Core.Spec.Reason’,
                     imported from ‘Test.Hspec.Core.Spec’ at src/Test/Validity/Utils.hs:29:1-27
                     (and originally defined in ‘hspec-core-2.11.1:Test.Hspec.Core.Example’)
           |                                                                                                                        
       110 |           else Failure Nothing $ Reason "Should have failed but didn't."                                               
           |                                  ^^^^^^
```

**Comment by NorfairKing** [comment]
Should be fixed now.
