### PR TITLE
Fix compatibility with hspec-2.10.0

### LINKED ISSUE #106: genvalidity-hspec doesn't build with hspec 2.10
```
[ 2 of 13] Compiling Test.Validity.Utils ( src/Test/Validity/Utils.hs, dist/build/Test/Validity/Utils.dyn_o )

src/Test/Validity/Utils.hs:71:57: error:
    • Couldn't match type: [SpecTree b]
                     with: (base-4.15.1.0:Data.Semigroup.Internal.Endo Config,
                            [SpecTree b])
      Expected: (r,
                 (base-4.15.1.0:Data.Semigroup.Internal.Endo Config, [SpecTree a]))
                -> (r,
                    (base-4.15.1.0:Data.Semigroup.Internal.Endo Config, [SpecTree b]))
        Actual: (r, [SpecTree a]) -> (r, [SpecTree b])
    • In the first argument of ‘fmap’, namely ‘(second (map f))’
      In the first argument of ‘mapWriterT’, namely
        ‘(fmap (second (map f)))’
      In the first argument of ‘SpecM’, namely
        ‘(mapWriterT (fmap (second (map f))) specs)’
    • Relevant bindings include
        f :: SpecTree a -> SpecTree b
          (bound at src/Test/Validity/Utils.hs:71:14)
        mapSpecTree' :: (SpecTree a -> SpecTree b)
                        -> SpecM a r -> SpecM b r
          (bound at src/Test/Validity/Utils.hs:71:1)
   |
71 | mapSpecTree' f (SpecM specs) = SpecM (mapWriterT (fmap (second (map f))) specs)
   |                                                         ^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by felixonmars**
Fixes #106

### CODE REVIEW

**Comment by NorfairKing** [comment]
@felixonmars CI fails because we need backward compatibility.

**Comment by sol** [comment]
Hold off with meeting for a second.

File: genvalidity-hspec/src/Test/Validity/Utils.hs [hunk 1]
```diff
@@ -68,7 +69,11 @@ instance Functor Anon where
...
 -- https://github.com/hspec/hspec/commit/020c7ecc4a73c24af38e9fab049f60bb9aec6981#diff-29cb22f0ef6e98086a71fc045847bd21L22
 mapSpecTree' :: (SpecTree a -> SpecTree b) -> SpecM a r -> SpecM b r
+#if MIN_VERSION_hspec(2,10,0)
+mapSpecTree' f (SpecM specs) = SpecM (mapWriterT (fmap (second (fmap (map f)))) specs)
+#else
 mapSpecTree' f (SpecM specs) = SpecM (mapWriterT (fmap (second (map f))) specs)
+#endif
 
 -- | Asserts that a given 'Spec' tree fails _somewhere_.
 --
```
Comment (sol) [inline genvalidity-hspec/src/Test/Validity/Utils.hs:79]: I think you don’t really need `mapSpecTree'` to implement `failsBecause`.

Something like this should work:

```haskell
failsBecause :: HasCallStack => String -> SpecWith () -> SpecWith ()
failsBecause s sp = it s $ do
    let conf = defaultConfig {configFormatter = Just silent}
    r <- hspecWithResult conf sp
    let succesful = summaryExamples r > 0 && summaryFailures r > 0
    throwIO $ produceResult succesful
```

Comment (sol) [reply genvalidity-hspec/src/Test/Validity/Utils.hs:79]: @NorfairKing the only difference here is that the spec item will have a location for the call site of `failsBecause`. That’s usually what you want. If it is not suitable for some reason then remove the location with `mapSpecItem_`.

Doing it that way is future proof and does not require `CPP`.

Comment (NorfairKing) [reply genvalidity-hspec/src/Test/Validity/Utils.hs:79]: `failsBecause` can be removed IMO, if that would help.

**Comment by felixonmars** [comment]
Thanks. We are packaging `genvalidity-hspec` for Arch only because `path` still uses it for the test suite. Since `path` doesn't use `failsBecause`, removing it won't cause any trouble to us.

For this repository, we need to adjust the test suite of `genvalidity-hspec-hashable` though, as `failsBecause` is still used there.

**Comment by NorfairKing** [comment]
> For this repository, we need to adjust the test suite of genvalidity-hspec-hashable though, as failsBecause is still used there.

I'm fine with removing that test and using a comment like "this would fail because ..." instead.

**Comment by sol** [comment]
This PR already works. So I guess merging this “as is” would still better than removing `failsBecause` (+ having to adapt `genvalidity-hspec-hashable` + risking to break other people’s code).

**Comment by NorfairKing** [comment]
@felixonmars Do you need this to be released to hackage?

**Comment by felixonmars** [comment]
> @felixonmars Do you need this to be released to hackage?

We've already cherry-picked the fix for now, but releasing a new version would still help. (Should be also true for Stackage and also distro)
